/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/prescreens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Indicative limit band from a hashed ID (G-12) */
        post: operations["createPrescreen"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/offers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an offer set for an order, loan request or restock */
        post: operations["createOfferRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/offers/{offerRequestId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch an offer set (idempotent replay) */
        get: operations["getOfferSet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/consents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Store a signed consent receipt for one source (D-30) */
        post: operations["createConsent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customers/{customerRef}/consents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Consents of a customer */
        get: operations["listConsents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/consents/{receiptId}/withdraw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Withdraw a consent */
        post: operations["withdrawConsent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ekyc/verifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify chip CCCD + face (simulated in the MVP) */
        post: operations["createEkycVerification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customers/{customerRef}/limit-ladder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ladder, limit and the data used per rung (R-16) */
        get: operations["getLimitLadder"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assessments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Assess and decide (tiered waterfall, F-02) */
        post: operations["createAssessment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/decisions/{decisionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch a decision */
        get: operations["getDecision"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contracts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create the HLB contract for an approved decision (D-32) */
        post: operations["createContract"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contracts/{contractId}/sign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign with OTP; books the loan */
        post: operations["signContract"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customers/{customerRef}/loans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Loans of a customer */
        get: operations["listLoans"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/loans/{loanId}/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Repay an instalment */
        post: operations["createPayment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/loans/{loanId}/settlement-quote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Early-settlement quote (no hidden fee) */
        get: operations["getSettlementQuote"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/webhooks/refunds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Partner → CreditPulse: return or refund on the order (F-09) */
        post: operations["receiveRefundEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/webhooks/payouts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Grab → CreditPulse: payout cycle income (F-08) */
        post: operations["receivePayoutEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/webhooks/settlements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sổ Bán Hàng → CreditPulse: settlement received (F-07) */
        post: operations["receiveSettlementEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customers/{customerRef}/graduation-offer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Graduation and referral payload (D-31) */
        get: operations["getGraduationOffer"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/console/decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Decision log */
        get: operations["listDecisions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/console/data-sources/ranking": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Alternative-data ranking and weights (R-16, D-20) */
        get: operations["getRanking"];
        /** Edit weights (must sum to 1) */
        put: operations["updateRankingWeights"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/console/manual-queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Manual tier queue */
        get: operations["listManualCases"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/console/manual-queue/{caseId}/resolution": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve or decline a manual case */
        post: operations["resolveManualCase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/console/learning-loop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Test band and champion–challenger (F-10) */
        get: operations["getLearningLoop"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/console/consent-ledger": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Consent ledger */
        get: operations["listConsentLedger"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/console/tia": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cross-border TIA register status */
        get: operations["getTiaStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/console/policies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Guardrail policy (F-06) */
        get: operations["getPolicy"];
        /** Edit guardrail policy; logged */
        put: operations["updatePolicy"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/console/partners": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Partners and products */
        get: operations["listPartners"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/console/partners/{partnerId}/test-webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send a test webhook */
        post: operations["sendTestWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/console/api-calls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** API inspector timeline */
        get: operations["listApiCalls"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/demo/scenario": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Force a scenario (mock mode only) */
        post: operations["setDemoScenario"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/demo/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset fixtures (mock mode only) */
        post: operations["resetDemoData"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/console/audit-log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Audit log of operator changes (who, when, what) */
        get: operations["listAuditLog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Problem: {
            type: string;
            title: string;
            status: number;
            detail?: string;
            errors?: {
                field?: string;
                message?: string;
            }[];
        };
        Money: {
            /** @description VND has no minor unit; amount is whole VND */
            amount: number;
            /** @enum {string} */
            currency: "VND";
        };
        /** @enum {string} */
        PartnerId: "viettel-money" | "grab" | "so-ban-hang";
        /**
         * @description D-37: one API, three product types
         * @enum {string}
         */
        ProductType: "PAYMENT_INSTALLMENT" | "DRIVER_INSTANT_LOAN" | "SELLER_FUNDING";
        /** @enum {string} */
        Segment: "SEG-1" | "SEG-2" | "SEG-3" | "SEG-4" | "SEG-5";
        /**
         * @description Step 07 §4 catalogue
         * @enum {string}
         */
        SourceId: "B-01" | "B-02" | "AD-01" | "AD-02" | "AD-03" | "AD-04" | "AD-05" | "AD-06" | "AD-07" | "AD-08" | "AD-09" | "AD-10";
        /** @enum {string} */
        RatingOutput: "RG" | "AF" | "IN" | "LM";
        /** @enum {string} */
        InterestPayer: "CUSTOMER" | "MERCHANT";
        /** @enum {string} */
        DecisionOutcome: "APPROVED" | "DECLINED" | "MANUAL_REVIEW";
        /** @enum {string} */
        DecisionTier: "STP" | "MANUAL";
        /** @enum {string} */
        ConsentStatus: "GRANTED" | "WITHDRAWN";
        /** @enum {string} */
        EkycMethod: "NFC_CHIP" | "CAPTURE_FALLBACK";
        /** @enum {string} */
        EkycStatus: "PASSED" | "FAILED" | "RETRY";
        /** @enum {string} */
        LoanStatus: "ACTIVE" | "PAUSED" | "LATE" | "SETTLED";
        /** @enum {string} */
        ScenarioName: "APPROVE" | "THIN_FILE" | "NOT_APPROVED" | "MANUAL_REVIEW" | "SLOW" | "EKYC_FAIL" | "SOURCE_DOWN" | "SESSION_EXPIRED";
        SourceUse: {
            sourceId: components["schemas"]["SourceId"];
            name: string;
            rank: number;
            outputs: components["schemas"]["RatingOutput"][];
            connected: boolean;
            role: string;
            weightScore: number;
            /** @description Variables read from this source for the decision (operator view) */
            variablesRead?: string[];
            costVnd?: number;
            latencyMs?: number;
        };
        PrescreenRequest: {
            partnerId: components["schemas"]["PartnerId"];
            hashedCustomerId: string;
        };
        PrescreenResult: {
            eligible: boolean;
            bandMin?: components["schemas"]["Money"];
            bandMax?: components["schemas"]["Money"];
            rung?: number;
            /** @description Why the customer is not eligible, in user language (e.g. a driver under 3 months). Present only when eligible is false. */
            reason?: string;
            /** Format: date-time */
            validUntil?: string;
        };
        OfferRequestCreate: {
            partnerId: components["schemas"]["PartnerId"];
            productType: components["schemas"]["ProductType"];
            customerRef: string;
            orderRef?: string;
            amount: components["schemas"]["Money"];
            consentReceiptIds?: string[];
        };
        Package: {
            packageId: string;
            tenorMonths: number;
            monthlyInstalment: components["schemas"]["Money"];
            totalPayable: components["schemas"]["Money"];
            /** @description Effective annual rate, e.g. 0.125 = 12.5% */
            eir: number;
            interestPayer: components["schemas"]["InterestPayer"];
            available: boolean;
            disabledReason?: string;
        };
        NextRung: {
            sourceId: components["schemas"]["SourceId"];
            name?: string;
            rank?: number;
            unlockLimit: components["schemas"]["Money"];
        };
        OfferSet: {
            /** Format: uuid */
            offerRequestId: string;
            limit: components["schemas"]["Money"];
            rung: number;
            packages: components["schemas"]["Package"][];
            reasonCodes: string[];
            nextRung?: components["schemas"]["NextRung"];
            explanationText?: string;
            /** Format: date-time */
            expiresAt: string;
            lockup: string;
        };
        ConsentCreate: {
            customerRef: string;
            partnerId: components["schemas"]["PartnerId"];
            sourceId: components["schemas"]["SourceId"];
            purpose?: string;
            textVersion: string;
            signature: string;
            /** Format: date-time */
            grantedAt?: string;
        };
        ConsentReceipt: {
            /** Format: uuid */
            receiptId: string;
            customerRef: string;
            partnerId?: components["schemas"]["PartnerId"];
            sourceId: components["schemas"]["SourceId"];
            purpose?: string;
            status: components["schemas"]["ConsentStatus"];
            /** Format: date-time */
            grantedAt?: string;
            /** Format: date-time */
            withdrawnAt?: string;
        };
        EkycRequest: {
            customerRef: string;
            method: components["schemas"]["EkycMethod"];
            chipPayloadRef?: string;
            faceCaptureRef?: string;
        };
        EkycResult: {
            /** Format: uuid */
            verificationId: string;
            status: components["schemas"]["EkycStatus"];
            reasonCode?: string;
            /** Format: date-time */
            reusableUntil?: string;
        };
        LadderRung: {
            rung: number;
            cap: components["schemas"]["Money"];
            reached: boolean;
            sources: components["schemas"]["SourceUse"][];
            unlocksText?: string;
        };
        LimitLadder: {
            customerRef: string;
            segment: components["schemas"]["Segment"];
            currentRung: number;
            currentLimit: components["schemas"]["Money"];
            rungs: components["schemas"]["LadderRung"][];
            nextSuggestion?: components["schemas"]["NextRung"];
            /** @enum {string} */
            cicState: "NO_FILE" | "FILE_FOUND" | "NOT_QUERIED";
        };
        AssessmentCreate: {
            customerRef: string;
            /** Format: uuid */
            offerRequestId?: string;
            packageId?: string;
            productType: components["schemas"]["ProductType"];
            amount: components["schemas"]["Money"];
            connectSources?: components["schemas"]["SourceId"][];
        };
        WaterfallStep: {
            order: number;
            sourceId: components["schemas"]["SourceId"];
            /** @enum {string} */
            status: "QUERIED" | "SKIPPED" | "UNAVAILABLE";
            costVnd?: number;
            latencyMs?: number;
            stopReason?: string;
        };
        Ratings: {
            /** @enum {string} */
            riskGrade?: "A" | "B" | "C" | "D" | "E";
            affordability?: components["schemas"]["Money"];
            /** @enum {string} */
            integrity?: "PASS" | "REVIEW" | "FAIL";
            limit?: components["schemas"]["Money"];
        };
        Decision: {
            /** Format: uuid */
            decisionId: string;
            outcome: components["schemas"]["DecisionOutcome"];
            tier: components["schemas"]["DecisionTier"];
            approvedAmount?: components["schemas"]["Money"];
            tenorMonths?: number;
            reasonCodes: string[];
            explanationText: string;
            dataUsed: components["schemas"]["SourceUse"][];
            ratings: components["schemas"]["Ratings"];
            waterfall: components["schemas"]["WaterfallStep"][];
            nextRung?: components["schemas"]["NextRung"];
            /** Format: date-time */
            retryAfter?: string;
            latencyMs: number;
            /** Format: date-time */
            decidedAt: string;
        };
        ContractCreate: {
            /** Format: uuid */
            decisionId: string;
            packageId: string;
        };
        Instalment: {
            number: number;
            /** Format: date */
            dueDate: string;
            amount: components["schemas"]["Money"];
            /** @enum {string} */
            status?: "DUE" | "PAID" | "LATE" | "PAUSED";
        };
        Contract: {
            /** Format: uuid */
            contractId: string;
            lender: string;
            amount: components["schemas"]["Money"];
            tenorMonths: number;
            totalPayable: components["schemas"]["Money"];
            eir: number;
            schedule: components["schemas"]["Instalment"][];
            keyFacts: string[];
            /** @enum {string} */
            status: "DRAFT" | "SIGNED" | "EXPIRED";
        };
        ContractSign: {
            otp: string;
        };
        Loan: {
            /** Format: uuid */
            loanId: string;
            customerRef: string;
            partnerId: components["schemas"]["PartnerId"];
            productType: components["schemas"]["ProductType"];
            status: components["schemas"]["LoanStatus"];
            principalRemaining: components["schemas"]["Money"];
            totalRemaining: components["schemas"]["Money"];
            eir: number;
            schedule: components["schemas"]["Instalment"][];
            /** Format: date */
            pauseUntil?: string;
        };
        PaymentCreate: {
            amount: components["schemas"]["Money"];
        };
        SettlementQuote: {
            /** Format: uuid */
            loanId: string;
            payoff: components["schemas"]["Money"];
            interestSaved?: components["schemas"]["Money"];
            /** Format: date-time */
            validUntil?: string;
        };
        RefundEvent: {
            /** Format: uuid */
            loanId: string;
            orderRef: string;
            refundAmount: components["schemas"]["Money"];
            reason?: string;
        };
        RefundResult: {
            /** Format: uuid */
            loanId: string;
            newPrincipal: components["schemas"]["Money"];
            newSchedule?: components["schemas"]["Instalment"][];
            /** Format: date */
            pauseUntil: string;
            adverseCicReported?: boolean;
        };
        PayoutEvent: {
            /** Format: uuid */
            loanId: string;
            cycleId: string;
            incomeAmount: components["schemas"]["Money"];
        };
        DeductionResult: {
            /** Format: uuid */
            loanId: string;
            cycleId: string;
            deducted: components["schemas"]["Money"];
            reason?: string;
            remaining?: components["schemas"]["Money"];
        };
        SettlementEvent: {
            /** Format: uuid */
            loanId: string;
            settlementId: string;
            grossAmount: components["schemas"]["Money"];
        };
        GraduationOffer: {
            customerRef: string;
            newLimit: components["schemas"]["Money"];
            productOffers?: string[];
            merchantCode?: string;
        };
        DecisionSummary: {
            /** Format: uuid */
            decisionId: string;
            customerMask: string;
            partnerId: components["schemas"]["PartnerId"];
            productType: components["schemas"]["ProductType"];
            amount: components["schemas"]["Money"];
            outcome: components["schemas"]["DecisionOutcome"];
            tier: components["schemas"]["DecisionTier"];
            latencyMs: number;
            /** Format: date-time */
            decidedAt: string;
        };
        DecisionPage: {
            items: components["schemas"]["DecisionSummary"][];
            page: number;
            size: number;
            totalItems: number;
        };
        RankingWeights: {
            predictive: number;
            coverage: number;
            cost: number;
            access: number;
            legal: number;
        };
        RankedSource: {
            sourceId: components["schemas"]["SourceId"];
            name: string;
            rank: number;
            score: number;
            ratings: {
                predictive?: number;
                coverage?: number;
                cost?: number;
                access?: number;
                legal?: number;
            };
        };
        Ranking: {
            weights: components["schemas"]["RankingWeights"];
            sources: components["schemas"]["RankedSource"][];
            waterfallOrder: components["schemas"]["SourceId"][];
            segmentRungMatrix: {
                segment?: components["schemas"]["Segment"];
                rungs?: components["schemas"]["SourceId"][][];
            }[];
        };
        ManualCase: {
            /** Format: uuid */
            caseId: string;
            /** Format: uuid */
            decisionId: string;
            /** Format: date-time */
            slaDueAt: string;
            /** @enum {string} */
            status: "OPEN" | "RESOLVED";
            suggestedAction: string;
        };
        ManualResolution: {
            /** @enum {string} */
            action: "APPROVE" | "DECLINE";
            reasonCode: string;
        };
        LearningLoop: {
            testBandShare: number;
            champion: {
                name?: string;
                approvalRate?: number;
                badRate?: number;
            };
            challenger: {
                name?: string;
                approvalRate?: number;
                badRate?: number;
            };
            wrongfulDeclineEstimate: number;
            modelDocUrl?: string;
        };
        ConsentLedgerEntry: {
            /** Format: uuid */
            receiptId: string;
            customerMask: string;
            partnerId: components["schemas"]["PartnerId"];
            sourceId: components["schemas"]["SourceId"];
            purpose: string;
            status: components["schemas"]["ConsentStatus"];
            /** Format: date-time */
            at: string;
        };
        TiaStatus: {
            /** @enum {string} */
            status: "NOT_STARTED" | "IN_PROGRESS" | "FILED";
            /** Format: date-time */
            filedAt?: string;
            note?: string;
        };
        Policy: {
            dtiCap: number;
            maxOpenLoans: number;
            cicRefreshOnLimitChange: boolean;
            testBandShare: number;
            rungCaps: components["schemas"]["Money"][];
            /** @description Model currently serving decisions; the challenger is the other one */
            championModel?: string;
        };
        Partner: {
            partnerId: components["schemas"]["PartnerId"];
            name: string;
            products: components["schemas"]["ProductType"][];
            webhookUrl: string;
            settlementAccountMask: string;
            sandboxKeyMask: string;
        };
        ApiCall: {
            /** Format: uuid */
            callId: string;
            flow: string;
            method: string;
            path: string;
            status: number;
            latencyMs: number;
            idempotencyKey: string;
            request: {
                [key: string]: unknown;
            };
            response: {
                [key: string]: unknown;
            };
            screen: string;
            /** Format: date-time */
            at: string;
        };
        ScenarioSet: {
            scenario: components["schemas"]["ScenarioName"];
        };
        AuditEntry: {
            /** Format: date-time */
            at: string;
            /** @description e.g. ranking.weights, policy.update, manual.resolve, learning.promote */
            action: string;
            /** @description Operator who made the change */
            actor: string;
            detail: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createPrescreen: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "partnerId": "viettel-money",
                 *       "hashedCustomerId": "h_9f2c…khoa"
                 *     }
                 */
                "application/json": components["schemas"]["PrescreenRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "eligible": true,
                     *       "bandMin": {
                     *         "amount": 5000000,
                     *         "currency": "VND"
                     *       },
                     *       "bandMax": {
                     *         "amount": 30000000,
                     *         "currency": "VND"
                     *       },
                     *       "rung": 4,
                     *       "validUntil": "2026-10-10T00:00:00Z"
                     *     }
                     */
                    "application/json": components["schemas"]["PrescreenResult"];
                };
            };
            /** @description Problem */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    createOfferRequest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "partnerId": "viettel-money",
                 *       "productType": "PAYMENT_INSTALLMENT",
                 *       "customerRef": "cus_mai",
                 *       "orderRef": "SPE-2026-0001",
                 *       "amount": {
                 *         "amount": 12000000,
                 *         "currency": "VND"
                 *       },
                 *       "consentReceiptIds": []
                 *     }
                 */
                "application/json": components["schemas"]["OfferRequestCreate"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "offerRequestId": "b1c0e3a2-6f7d-4b29-8c11-0d2e9a000001",
                     *       "limit": {
                     *         "amount": 15000000,
                     *         "currency": "VND"
                     *       },
                     *       "rung": 3,
                     *       "packages": [
                     *         {
                     *           "packageId": "pkg-6",
                     *           "tenorMonths": 6,
                     *           "monthlyInstalment": {
                     *             "amount": 2000000,
                     *             "currency": "VND"
                     *           },
                     *           "totalPayable": {
                     *             "amount": 12000000,
                     *             "currency": "VND"
                     *           },
                     *           "eir": 0,
                     *           "interestPayer": "MERCHANT",
                     *           "available": true
                     *         },
                     *         {
                     *           "packageId": "pkg-9",
                     *           "tenorMonths": 9,
                     *           "monthlyInstalment": {
                     *             "amount": 1400000,
                     *             "currency": "VND"
                     *           },
                     *           "totalPayable": {
                     *             "amount": 12600000,
                     *             "currency": "VND"
                     *           },
                     *           "eir": 0.125,
                     *           "interestPayer": "CUSTOMER",
                     *           "available": true
                     *         },
                     *         {
                     *           "packageId": "pkg-12",
                     *           "tenorMonths": 12,
                     *           "monthlyInstalment": {
                     *             "amount": 1085000,
                     *             "currency": "VND"
                     *           },
                     *           "totalPayable": {
                     *             "amount": 13020000,
                     *             "currency": "VND"
                     *           },
                     *           "eir": 0.165,
                     *           "interestPayer": "CUSTOMER",
                     *           "available": true
                     *         }
                     *       ],
                     *       "reasonCodes": [],
                     *       "nextRung": {
                     *         "sourceId": "AD-03",
                     *         "name": "Tài khoản lương HLB",
                     *         "rank": 3,
                     *         "unlockLimit": {
                     *           "amount": 30000000,
                     *           "currency": "VND"
                     *         }
                     *       },
                     *       "expiresAt": "2026-10-03T09:30:00Z",
                     *       "lockup": "Được cung cấp bởi Hong Leong Bank"
                     *     }
                     */
                    "application/json": components["schemas"]["OfferSet"];
                };
            };
            /** @description Problem */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getOfferSet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                offerRequestId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "offerRequestId": "b1c0e3a2-6f7d-4b29-8c11-0d2e9a000001",
                     *       "limit": {
                     *         "amount": 15000000,
                     *         "currency": "VND"
                     *       },
                     *       "rung": 3,
                     *       "packages": [
                     *         {
                     *           "packageId": "pkg-6",
                     *           "tenorMonths": 6,
                     *           "monthlyInstalment": {
                     *             "amount": 2000000,
                     *             "currency": "VND"
                     *           },
                     *           "totalPayable": {
                     *             "amount": 12000000,
                     *             "currency": "VND"
                     *           },
                     *           "eir": 0,
                     *           "interestPayer": "MERCHANT",
                     *           "available": true
                     *         },
                     *         {
                     *           "packageId": "pkg-9",
                     *           "tenorMonths": 9,
                     *           "monthlyInstalment": {
                     *             "amount": 1400000,
                     *             "currency": "VND"
                     *           },
                     *           "totalPayable": {
                     *             "amount": 12600000,
                     *             "currency": "VND"
                     *           },
                     *           "eir": 0.125,
                     *           "interestPayer": "CUSTOMER",
                     *           "available": true
                     *         },
                     *         {
                     *           "packageId": "pkg-12",
                     *           "tenorMonths": 12,
                     *           "monthlyInstalment": {
                     *             "amount": 1085000,
                     *             "currency": "VND"
                     *           },
                     *           "totalPayable": {
                     *             "amount": 13020000,
                     *             "currency": "VND"
                     *           },
                     *           "eir": 0.165,
                     *           "interestPayer": "CUSTOMER",
                     *           "available": true
                     *         }
                     *       ],
                     *       "reasonCodes": [],
                     *       "nextRung": {
                     *         "sourceId": "AD-03",
                     *         "name": "Tài khoản lương HLB",
                     *         "rank": 3,
                     *         "unlockLimit": {
                     *           "amount": 30000000,
                     *           "currency": "VND"
                     *         }
                     *       },
                     *       "expiresAt": "2026-10-03T09:30:00Z",
                     *       "lockup": "Được cung cấp bởi Hong Leong Bank"
                     *     }
                     */
                    "application/json": components["schemas"]["OfferSet"];
                };
            };
            /** @description Problem */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    createConsent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "customerRef": "cus_mai",
                 *       "partnerId": "viettel-money",
                 *       "sourceId": "AD-01",
                 *       "purpose": "Đánh giá khả năng trả nợ",
                 *       "textVersion": "hlb-consent-v1",
                 *       "signature": "sig_demo",
                 *       "grantedAt": "2026-10-03T09:10:00Z"
                 *     }
                 */
                "application/json": components["schemas"]["ConsentCreate"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "receiptId": "c0a1f0aa-1111-4d2e-9c3b-0000000000a1",
                     *       "customerRef": "cus_mai",
                     *       "partnerId": "viettel-money",
                     *       "sourceId": "AD-01",
                     *       "purpose": "Đánh giá khả năng trả nợ",
                     *       "status": "GRANTED",
                     *       "grantedAt": "2026-10-03T09:10:00Z"
                     *     }
                     */
                    "application/json": components["schemas"]["ConsentReceipt"];
                };
            };
            /** @description Problem */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listConsents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                customerRef: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsentReceipt"][];
                };
            };
            /** @description Problem */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    withdrawConsent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                receiptId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsentReceipt"];
                };
            };
            /** @description Problem */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    createEkycVerification: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "customerRef": "cus_mai",
                 *       "method": "NFC_CHIP",
                 *       "chipPayloadRef": "chip_demo",
                 *       "faceCaptureRef": "face_demo"
                 *     }
                 */
                "application/json": components["schemas"]["EkycRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "verificationId": "e0a1f0aa-2222-4d2e-9c3b-0000000000e1",
                     *       "status": "PASSED",
                     *       "reusableUntil": "2026-10-03T10:10:00Z"
                     *     }
                     */
                    "application/json": components["schemas"]["EkycResult"];
                };
            };
            /** @description Problem */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getLimitLadder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                customerRef: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "customerRef": "cus_mai",
                     *       "segment": "SEG-2",
                     *       "currentRung": 3,
                     *       "currentLimit": {
                     *         "amount": 15000000,
                     *         "currency": "VND"
                     *       },
                     *       "cicState": "NO_FILE",
                     *       "rungs": [
                     *         {
                     *           "rung": 1,
                     *           "cap": {
                     *             "amount": 3000000,
                     *             "currency": "VND"
                     *           },
                     *           "reached": true,
                     *           "sources": [
                     *             {
                     *               "sourceId": "B-01",
                     *               "name": "CCCD chip + khuôn mặt",
                     *               "rank": 0
                     *             },
                     *             {
                     *               "sourceId": "AD-02",
                     *               "name": "Dữ liệu thanh toán và thiết bị",
                     *               "rank": 2,
                     *               "outputs": [
                     *                 "IN"
                     *               ],
                     *               "connected": true
                     *             }
                     *           ]
                     *         },
                     *         {
                     *           "rung": 2,
                     *           "cap": {
                     *             "amount": 8000000,
                     *             "currency": "VND"
                     *           },
                     *           "reached": true,
                     *           "sources": [
                     *             {
                     *               "sourceId": "AD-01",
                     *               "name": "Lịch sử ví",
                     *               "rank": 1,
                     *               "outputs": [
                     *                 "RG",
                     *                 "AF"
                     *               ],
                     *               "connected": true
                     *             }
                     *           ]
                     *         },
                     *         {
                     *           "rung": 3,
                     *           "cap": {
                     *             "amount": 15000000,
                     *             "currency": "VND"
                     *           },
                     *           "reached": true,
                     *           "sources": [
                     *             {
                     *               "sourceId": "AD-05",
                     *               "name": "Thanh toán hóa đơn",
                     *               "rank": 5,
                     *               "outputs": [
                     *                 "RG"
                     *               ],
                     *               "connected": true
                     *             }
                     *           ]
                     *         }
                     *       ],
                     *       "nextSuggestion": {
                     *         "sourceId": "AD-03",
                     *         "name": "Tài khoản lương HLB",
                     *         "rank": 3,
                     *         "unlockLimit": {
                     *           "amount": 30000000,
                     *           "currency": "VND"
                     *         }
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["LimitLadder"];
                };
            };
            /** @description Problem */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    createAssessment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "customerRef": "cus_mai",
                 *       "offerRequestId": "b1c0e3a2-6f7d-4b29-8c11-0d2e9a000001",
                 *       "packageId": "pkg-6",
                 *       "productType": "PAYMENT_INSTALLMENT",
                 *       "amount": {
                 *         "amount": 12000000,
                 *         "currency": "VND"
                 *       },
                 *       "connectSources": [
                 *         "AD-01",
                 *         "AD-05"
                 *       ]
                 *     }
                 */
                "application/json": components["schemas"]["AssessmentCreate"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "decisionId": "7d3f6b9e-0c1a-4f64-9b1e-2a6a1c9b0001",
                     *       "outcome": "APPROVED",
                     *       "tier": "STP",
                     *       "approvedAmount": {
                     *         "amount": 12000000,
                     *         "currency": "VND"
                     *       },
                     *       "tenorMonths": 6,
                     *       "reasonCodes": [
                     *         "WALLET_INFLOW_STABLE",
                     *         "BILLS_ON_TIME"
                     *       ],
                     *       "explanationText": "Ví của bạn có thu nhập đều đặn 12 tháng; hóa đơn điện nước trả đúng hạn.",
                     *       "dataUsed": [
                     *         {
                     *           "sourceId": "AD-01",
                     *           "name": "Lịch sử ví Viettel Money",
                     *           "rank": 1,
                     *           "outputs": [
                     *             "RG",
                     *             "AF"
                     *           ],
                     *           "connected": true,
                     *           "role": "Thu nhập đều"
                     *         },
                     *         {
                     *           "sourceId": "AD-05",
                     *           "name": "Thanh toán hóa đơn",
                     *           "rank": 5,
                     *           "outputs": [
                     *             "RG"
                     *           ],
                     *           "connected": true,
                     *           "role": "Trả đúng hạn"
                     *         }
                     *       ],
                     *       "ratings": {
                     *         "riskGrade": "B",
                     *         "affordability": {
                     *           "amount": 3200000,
                     *           "currency": "VND"
                     *         },
                     *         "integrity": "PASS",
                     *         "limit": {
                     *           "amount": 15000000,
                     *           "currency": "VND"
                     *         }
                     *       },
                     *       "waterfall": [
                     *         {
                     *           "order": 1,
                     *           "sourceId": "AD-02",
                     *           "status": "QUERIED",
                     *           "costVnd": 0,
                     *           "latencyMs": 40
                     *         },
                     *         {
                     *           "order": 2,
                     *           "sourceId": "AD-01",
                     *           "status": "QUERIED",
                     *           "costVnd": 2000,
                     *           "latencyMs": 310,
                     *           "stopReason": "confident after AD-05"
                     *         },
                     *         {
                     *           "order": 3,
                     *           "sourceId": "AD-05",
                     *           "status": "QUERIED",
                     *           "costVnd": 1500,
                     *           "latencyMs": 250
                     *         }
                     *       ],
                     *       "nextRung": {
                     *         "sourceId": "AD-03",
                     *         "name": "Tài khoản lương HLB",
                     *         "rank": 3,
                     *         "unlockLimit": {
                     *           "amount": 30000000,
                     *           "currency": "VND"
                     *         }
                     *       },
                     *       "latencyMs": 1900,
                     *       "decidedAt": "2026-10-03T09:15:00Z"
                     *     }
                     */
                    "application/json": components["schemas"]["Decision"];
                };
            };
            /** @description Problem */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getDecision: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                decisionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "decisionId": "7d3f6b9e-0c1a-4f64-9b1e-2a6a1c9b0001",
                     *       "outcome": "APPROVED",
                     *       "tier": "STP",
                     *       "approvedAmount": {
                     *         "amount": 12000000,
                     *         "currency": "VND"
                     *       },
                     *       "tenorMonths": 6,
                     *       "reasonCodes": [
                     *         "WALLET_INFLOW_STABLE",
                     *         "BILLS_ON_TIME"
                     *       ],
                     *       "explanationText": "Ví của bạn có thu nhập đều đặn 12 tháng; hóa đơn điện nước trả đúng hạn.",
                     *       "dataUsed": [
                     *         {
                     *           "sourceId": "AD-01",
                     *           "name": "Lịch sử ví Viettel Money",
                     *           "rank": 1,
                     *           "outputs": [
                     *             "RG",
                     *             "AF"
                     *           ],
                     *           "connected": true,
                     *           "role": "Thu nhập đều"
                     *         },
                     *         {
                     *           "sourceId": "AD-05",
                     *           "name": "Thanh toán hóa đơn",
                     *           "rank": 5,
                     *           "outputs": [
                     *             "RG"
                     *           ],
                     *           "connected": true,
                     *           "role": "Trả đúng hạn"
                     *         }
                     *       ],
                     *       "ratings": {
                     *         "riskGrade": "B",
                     *         "affordability": {
                     *           "amount": 3200000,
                     *           "currency": "VND"
                     *         },
                     *         "integrity": "PASS",
                     *         "limit": {
                     *           "amount": 15000000,
                     *           "currency": "VND"
                     *         }
                     *       },
                     *       "waterfall": [
                     *         {
                     *           "order": 1,
                     *           "sourceId": "AD-02",
                     *           "status": "QUERIED",
                     *           "costVnd": 0,
                     *           "latencyMs": 40
                     *         },
                     *         {
                     *           "order": 2,
                     *           "sourceId": "AD-01",
                     *           "status": "QUERIED",
                     *           "costVnd": 2000,
                     *           "latencyMs": 310,
                     *           "stopReason": "confident after AD-05"
                     *         },
                     *         {
                     *           "order": 3,
                     *           "sourceId": "AD-05",
                     *           "status": "QUERIED",
                     *           "costVnd": 1500,
                     *           "latencyMs": 250
                     *         }
                     *       ],
                     *       "nextRung": {
                     *         "sourceId": "AD-03",
                     *         "name": "Tài khoản lương HLB",
                     *         "rank": 3,
                     *         "unlockLimit": {
                     *           "amount": 30000000,
                     *           "currency": "VND"
                     *         }
                     *       },
                     *       "latencyMs": 1900,
                     *       "decidedAt": "2026-10-03T09:15:00Z"
                     *     }
                     */
                    "application/json": components["schemas"]["Decision"];
                };
            };
            /** @description Problem */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    createContract: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "decisionId": "7d3f6b9e-0c1a-4f64-9b1e-2a6a1c9b0001",
                 *       "packageId": "pkg-6"
                 *     }
                 */
                "application/json": components["schemas"]["ContractCreate"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "contractId": "c1000000-0000-4000-8000-000000000001",
                     *       "lender": "Hong Leong Bank Vietnam",
                     *       "amount": {
                     *         "amount": 12000000,
                     *         "currency": "VND"
                     *       },
                     *       "tenorMonths": 6,
                     *       "totalPayable": {
                     *         "amount": 12000000,
                     *         "currency": "VND"
                     *       },
                     *       "eir": 0,
                     *       "schedule": [
                     *         {
                     *           "number": 1,
                     *           "dueDate": "2026-11-03",
                     *           "amount": {
                     *             "amount": 2000000,
                     *             "currency": "VND"
                     *           },
                     *           "status": "DUE"
                     *         }
                     *       ],
                     *       "keyFacts": [
                     *         "Không có phí ẩn"
                     *       ],
                     *       "status": "DRAFT"
                     *     }
                     */
                    "application/json": components["schemas"]["Contract"];
                };
            };
            /** @description Problem */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    signContract: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contractId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "otp": "123456"
                 *     }
                 */
                "application/json": components["schemas"]["ContractSign"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "loanId": "a1000000-0000-4000-8000-000000000001",
                     *       "customerRef": "cus_mai",
                     *       "partnerId": "viettel-money",
                     *       "productType": "PAYMENT_INSTALLMENT",
                     *       "status": "ACTIVE",
                     *       "principalRemaining": {
                     *         "amount": 12000000,
                     *         "currency": "VND"
                     *       },
                     *       "totalRemaining": {
                     *         "amount": 12000000,
                     *         "currency": "VND"
                     *       },
                     *       "eir": 0,
                     *       "schedule": []
                     *     }
                     */
                    "application/json": components["schemas"]["Loan"];
                };
            };
            /** @description Problem */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listLoans: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                customerRef: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Loan"][];
                };
            };
            /** @description Problem */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    createPayment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                loanId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "amount": {
                 *         "amount": 2000000,
                 *         "currency": "VND"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["PaymentCreate"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Loan"];
                };
            };
            /** @description Problem */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getSettlementQuote: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                loanId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettlementQuote"];
                };
            };
            /** @description Problem */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    receiveRefundEvent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "loanId": "a1000000-0000-4000-8000-000000000001",
                 *       "orderRef": "SPE-2026-0001",
                 *       "refundAmount": {
                 *         "amount": 3000000,
                 *         "currency": "VND"
                 *       },
                 *       "reason": "RETURN"
                 *     }
                 */
                "application/json": components["schemas"]["RefundEvent"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "loanId": "a1000000-0000-4000-8000-000000000001",
                     *       "newPrincipal": {
                     *         "amount": 9000000,
                     *         "currency": "VND"
                     *       },
                     *       "pauseUntil": "2026-11-15",
                     *       "adverseCicReported": false
                     *     }
                     */
                    "application/json": components["schemas"]["RefundResult"];
                };
            };
            /** @description Problem */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    receivePayoutEvent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "loanId": "a2000000-0000-4000-8000-000000000002",
                 *       "cycleId": "2026-W40",
                 *       "incomeAmount": {
                 *         "amount": 0,
                 *         "currency": "VND"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["PayoutEvent"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeductionResult"];
                };
            };
            /** @description Problem */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    receiveSettlementEvent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "loanId": "a3000000-0000-4000-8000-000000000003",
                 *       "settlementId": "stl_001",
                 *       "grossAmount": {
                 *         "amount": 4000000,
                 *         "currency": "VND"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["SettlementEvent"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeductionResult"];
                };
            };
            /** @description Problem */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getGraduationOffer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                customerRef: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "customerRef": "cus_mai",
                     *       "newLimit": {
                     *         "amount": 20000000,
                     *         "currency": "VND"
                     *       },
                     *       "productOffers": [
                     *         "HLB_CARD"
                     *       ],
                     *       "merchantCode": "SHOP-10"
                     *     }
                     */
                    "application/json": components["schemas"]["GraduationOffer"];
                };
            };
            /** @description Problem */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listDecisions: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
                partnerId?: string;
                outcome?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionPage"];
                };
            };
            /** @description Problem */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getRanking: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "weights": {
                     *         "predictive": 0.3,
                     *         "coverage": 0.25,
                     *         "cost": 0.15,
                     *         "access": 0.15,
                     *         "legal": 0.15
                     *       },
                     *       "sources": [
                     *         {
                     *           "sourceId": "AD-01",
                     *           "name": "Lịch sử ví",
                     *           "rank": 1,
                     *           "score": 4.1,
                     *           "ratings": {
                     *             "predictive": 4,
                     *             "coverage": 5,
                     *             "cost": 4,
                     *             "access": 4,
                     *             "legal": 3
                     *           }
                     *         }
                     *       ],
                     *       "waterfallOrder": [
                     *         "AD-02",
                     *         "AD-01",
                     *         "AD-05"
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["Ranking"];
                };
            };
            /** @description Problem */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    updateRankingWeights: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "predictive": 0.3,
                 *       "coverage": 0.25,
                 *       "cost": 0.15,
                 *       "access": 0.15,
                 *       "legal": 0.15
                 *     }
                 */
                "application/json": components["schemas"]["RankingWeights"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ranking"];
                };
            };
            /** @description Problem */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listManualCases: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManualCase"][];
                };
            };
            /** @description Problem */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    resolveManualCase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                caseId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "action": "APPROVE",
                 *       "reasonCode": "DOC_CONFIRMED"
                 *     }
                 */
                "application/json": components["schemas"]["ManualResolution"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManualCase"];
                };
            };
            /** @description Problem */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getLearningLoop: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "testBandShare": 0.03,
                     *       "champion": {
                     *         "name": "v1",
                     *         "approvalRate": 0.62,
                     *         "badRate": 0.031
                     *       },
                     *       "challenger": {
                     *         "name": "v2",
                     *         "approvalRate": 0.66,
                     *         "badRate": 0.033
                     *       },
                     *       "wrongfulDeclineEstimate": 0.04
                     *     }
                     */
                    "application/json": components["schemas"]["LearningLoop"];
                };
            };
            /** @description Problem */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listConsentLedger: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsentLedgerEntry"][];
                };
            };
            /** @description Problem */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getTiaStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "FILED",
                     *       "note": "Mô phỏng"
                     *     }
                     */
                    "application/json": components["schemas"]["TiaStatus"];
                };
            };
            /** @description Problem */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getPolicy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "dtiCap": 0.35,
                     *       "maxOpenLoans": 3,
                     *       "cicRefreshOnLimitChange": true,
                     *       "testBandShare": 0.03
                     *     }
                     */
                    "application/json": components["schemas"]["Policy"];
                };
            };
            /** @description Problem */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    updatePolicy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "dtiCap": 0.35,
                 *       "maxOpenLoans": 3,
                 *       "cicRefreshOnLimitChange": true
                 *     }
                 */
                "application/json": components["schemas"]["Policy"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Policy"];
                };
            };
            /** @description Problem */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listPartners: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example [
                     *       {
                     *         "partnerId": "viettel-money",
                     *         "name": "Viettel Money",
                     *         "products": [
                     *           "PAYMENT_INSTALLMENT"
                     *         ]
                     *       },
                     *       {
                     *         "partnerId": "grab",
                     *         "name": "Grab",
                     *         "products": [
                     *           "DRIVER_INSTANT_LOAN"
                     *         ]
                     *       },
                     *       {
                     *         "partnerId": "so-ban-hang",
                     *         "name": "Sổ Bán Hàng",
                     *         "products": [
                     *           "SELLER_FUNDING"
                     *         ]
                     *       }
                     *     ]
                     */
                    "application/json": components["schemas"]["Partner"][];
                };
            };
            /** @description Problem */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    sendTestWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                partnerId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiCall"];
                };
            };
            /** @description Problem */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listApiCalls: {
        parameters: {
            query?: {
                flow?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiCall"][];
                };
            };
            /** @description Problem */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    setDemoScenario: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "scenario": "THIN_FILE"
                 *     }
                 */
                "application/json": components["schemas"]["ScenarioSet"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Problem */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    resetDemoData: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Problem */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listAuditLog: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEntry"][];
                };
            };
        };
    };
}
